### ISSUE TITLE
Installing on Ubuntu

### ISSUE THREAD

**Issue by random9brat** [wzdwc/TexasPokerGame#2]
Hello wzdwc :),

Any chance of helping me install this on ubuntu? Im texas holdem poker fun and player, would love to see how this app works :)

Cheers.

**Comment by wzdwc** [comment]
The deployment is the same as CentOS, you can follow the README step by step([client](https://github.com/wzdwc/TexasPokerGame/tree/master/client),[server](https://github.com/wzdwc/TexasPokerGame/tree/master/server))

**Comment by imagazin** [comment]
Hey, thanks for the reply :) 

I think i have run server in the background on 7001 and i installed client which created me dist folder (i pointed nginx to that index.html file). I got my redis and mysql setup but when i connect to a client it writes me this:

![4444](https://user-images.githubusercontent.com/23549496/172045800-b8fc66c0-c1ab-4c24-a575-750b322fe89d.png)

Any changes you know what should i do? I would appreciate a lot any kind of help ;)

**Comment by random9brat** [comment]
Hey, thanks for the reply :) 

I think i have run server in the background on 7001 and i installed client which created me dist folder (i pointed nginx to that index.html file). I got my redis and mysql setup but when i connect to a client and try to create a account in register page it writes me this:

![4444](https://user-images.githubusercontent.com/23549496/172045800-b8fc66c0-c1ab-4c24-a575-750b322fe89d.png)

Any changes you know what should i do? I would appreciate a lot any kind of help ;)

**Comment by wzdwc** [comment]
In  "/client/src/utils/origin.ts" . 
 
export default {
  url: process.env.NODE_ENV !== 'production' ?
    process.env.NODE_ENV === 'develop' ? 'http://172.22.72.70:7001'
      : 'http://127.0.0.1:7001' : 'http://www.jojgame.com:7001',
  res: location.href.split('#')[0] + '#',
};
http://www.jojgame.com  == your domain
