### ISSUE TITLE
做下会报错

### ISSUE THREAD

**Issue by cycz** [wzdwc/TexasPokerGame#4]
![image](https://user-images.githubusercontent.com/25833606/187024098-ab2270b4-2b3f-4168-b6aa-274503c22f3b.png)

**Comment by wzdwc** [comment]
大概是你的后端的服务没跑起来，或者radis 有问题。你可以坐下之后，看看后端服务的日志。如果能截个图最好

**Comment by wzdwc** [comment]
已修复
