### ISSUE TITLE
老哥能给下安装教程吗

### ISSUE THREAD

**Issue by Ethanwain** [wzdwc/TexasPokerGame#7]
朋友间自己玩,用你的demo会退出,有安装教程么 依赖什么的?

**Comment by Ethanwain** [comment]
现在是服务端跑起来,客户端也跑起来,注册的时候提示失败

**Comment by Ethanwain** [comment]
show: false
text: "{"message":"Network Error","name":"Error","stack":"Error: Network Error\n at createError (webpack-internal:///./node_modules/axios/lib/core/createError.js:16:15)\n at XMLHttpRequest.handleError (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:83:14)","config":{"url":"http://127.0.0.1:7001/node/user/register","method":"post","data":"{\"userAccount\":\"admin\",\"password\":\"123456\",\"nickName\":\"admin\"}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","Authorization":"Bearer null"},"transformRequest":[null],"transformResponse":[null],"timeout":8000,"withCredentials":true,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1}}"
timeOut: 3000

**Comment by Ethanwain** [comment]
弄好了,原来是要改下origin.ts

**Comment by Ethanwain** [comment]
感觉运行速度有点慢啊,很容易卡死

**Comment by wzdwc** [comment]
应该还好吧，我们很少会卡死，最低配的阿里云服务器
